Project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls')),
    path('dashboard/', include('dashboard.urls'))
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from . import views
from django.urls import path

urlpatterns = [
    # ----------- category api -------------
    path('category/list/', views.category_list),
    path('category/detail/<int:id>/', views.category_detail),
    
    # ------------post api -----------------
    path('post/detail/<int:id>/', views.post_detail),
    path('post/list', views.post_list),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name =  'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('category-list/', views.list_category, name='category-list'),
    path('category-create/', views.create_category, name='category-create'),
    path('category-detail/<int:id>/', views.detail_category, name='category-detail'),
    path('category-edit/<int:id>/', views.edit_category, name='category-edit'),
    path('category-delete/<int:id>/', views.delete_category, name='category-delete'),
    
    
    path('register/', views.register, name='register'),
    path('log-in/', views.log_in, name='log_in'),
    path('log-out/', views.log_out, name='log_out'),

    path('region-list/', views.list_region, name='region-list'),
    path('region-create/', views.create_region, name='region-create'),
    path('region-detail/<int:id>/', views.detail_region, name='region-detail'),
    path('region-edit/<int:id>/', views.edit_region, name='region-edit'),
    path('region-delete/<int:id>/', views.delete_region, name='region-delete'),

    path('post-detail/<int:id>/', views.detail_post, name='post-detail'),
    path('post-create/', views.create_post, name='post-create'),
    path('post-edit/<int:id>/', views.edit_post, name='post-edit'),
    path('post-delete/<int:id>/', views.delete_post, name='post-delete'),
    path('post-list/', views.list_post, name='post-list'),
]

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from main import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from django.db.models import Q


@login_required(login_url='dashboard:log_in')
def index(request):
    category = models.Category.objects.all().count()

    context = {
        'category' : category
    }
    return render(request, 'dashboard/index.html')


#>>>>>>>>> Category create list edit delete detail <<<<<<<<<<<<<


@login_required(login_url='dashboard:log_in')
def create_category(request):
    if request.method == 'POST':
        try:
          name = request.POST['name']
          models.Category.objects.create(
            name=name
         )
          messages.success(request, 'Categoriyalar muvafiqiyatli tugatildi')
        except:
          messages.error(request, 'Categoryalar yaratishda xatolik')
    return render(request, 'dashboard/category/create.html')


@login_required(login_url='dashboard:log_in')
def list_category(request):
    category = models.Category.objects.all()
    context = {
        'category':category
    }
    return render(request, 'dashboard/category/list.html', context)


@login_required(login_url='dashboard:log_in')
def detail_category(request, id):
    category = models.Category.objects.get(id=id)
    context = {
        'category':category
    }
    return render(request, 'dashboard/category/detail.html', context)

@login_required(login_url='dashboard:log_in')
def edit_category(request, id):
    category = models.Category.objects.get(id=id)
    if request.method == 'POST':
        category.name = request.POST['name']
        category.save()
        messages.success(request, 'Kategoriyasini  muvoffaqiyatli o`zgartirildi')
        return redirect('dashboard:category-detail', category.id)
    context = {
        'category':category
    }
    return render(request, 'dashboard/category/edit.html', context)


@login_required(login_url='dashboard:log_in')
def delete_category(request, id):
    models.Category.objects.get(id=id).delete()
    messages.success(request, 'Categorylar muvafiqiyatli o`chirildi')
    return redirect('dashboard:category-list')

    
# >>>>>>>>>>> registry log_in  log_out query <<<<<<<<<<<<


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password_confirm = request.POST['password_confirm']
        if password == password_confirm:
            User.objects.create_user(
                username = username,
                password = password
            )
            user = authenticate(
            username = username, 
            password = password
            )
            if user:
                login(request, user)
                messages.success(request, 'Muvoffaqiyatli ro`yxatdan o`tdingiz')
                return redirect('dashboard:index')
            else:
                messages.success(request, 'Muvoffaqiyatsizlik qayta uring')
                return redirect('dashboard:register') 
                
    return render(request, 'dashboard/auth/register.html')

def log_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        # user = User.objects.get(username=username)
        user = authenticate(
            username = username, 
            password = password
            )
        if user:
            login(request, user)
            messages.success(request, 'Muvoffaqiyatli tizimga kirdiz ')
            return redirect('dashboard:index')
        else:
            messages.success(request, 'Muvoffaqiyatsizlik qayta uring ')
            return redirect('dashboard:log_in')

    return render(request, 'dashboard/auth/login.html')


def log_out(request):
    logout(request)
    return redirect('main:index')

def query(request):
    q = request.GET['q']
    category = models.Category.objects.filter(Q(name__icontains=q))

    context = {
        'category':category,
    }
    return render(request, 'dashboard/query.html', context)



#>>>>>>>>>Region list detail create edit <<<<<<<<<<<<<



def create_region(request):
    if request.method == 'POST':
        try:
          name = request.POST['name']
          models.Region.objects.create(
            name=name
         )
          messages.success(request, 'Regionalar muvafiqiyatli tugatildi')
        except:
          messages.error(request, 'Regionalar yaratishda xatolik')
    return render(request, 'dashboard/region/create.html')

def list_region(request):
    region = models.Region.objects.all()
    context = {
       'region':region
    }
    return render(request, 'dashboard/region/list.html', context)

def detail_region(request, id):
    region = models.Region.objects.get(id=id)
    context = {
       'region':region
    }
    return render(request, 'dashboard/region/detail.html', context)

def edit_region(request, id):
    region = models.Region.objects.get(id=id)
    if request.method == 'POST':
        region.name = request.POST['name']
        region.save()
        messages.success(request, 'Regionlar muvafiqiyatli o`zgartirildi')
        return redirect('dashboard:region-detail', region.id)
    return render(request, 'dashboard/region/edit.html')
    
def delete_region(request, id):
    models.Region.objects.get(id=id).delete()
    messages.success(request, 'Regionlar muvafiqiyatli o`chirildi')
    return redirect('dashboard:region-list')





#>>>>>>>>>Post list detail list edit <<<<<<<<<<<


def create_post(request):
    category = models.Category.objects.all()
    region = models.Region.objects.all()
    context = {
        'category':category,
         'region':region
    }
    if request.method == 'POST':
        try:
          title = request.POST['title']
          content = request.POST['content']
          category = request.POST['category']
          region = request.POST['region']
          models.Post.objects.create(
            title=title,
            content=content,
            category=category,
            region=region
         )
          messages.success(request, 'Postlar muvafiqiyatli tugatildi')
        except:
          messages.error(request, 'Postlar yaratishda xatolik')
    return render(request, 'dashboard/post/create.html', context)

def list_post(request):
    """post list"""
    post = models.Post.objects.all()
    context = {
       'post':post
    }
    return render(request, 'dashboard/post/list.html', context)

def detail_post(request, id):
    post = models.Post.objects.get(id=id)
    context = {
       'post':post
    }
    return render(request, 'dashboard/post/detail.html', context)

def edit_post(request, id):
    post = models.Post.objects.get(id=id)
    if request.method == 'POST':
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.category = request.POST['category']
        post.region = request.POST['region']
        post.save()
        messages.success(request, 'Postlar muvafiqiyatli o`zgartirildi')
        return redirect('dashboard:post-detail', post.id)
    return render(request, 'dashboard/post/edit.html')

def delete_post(request, id):
    models.Post.objects.get(id=id).delete()
    messages.success(request, 'Postlar muvafiqiyatli o`chirildi')
    return redirect('dashboard:post-list')

templates/dashboard/category/create.html
{% extends 'dashboard/base.html' %}
{% block content %}
            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">                                    
                                    <div class="page-title-right">
                                        <form class="d-flex">
                                            <div class="input-group">
                                                <input type="text" class="form-control form-control-light" id="dash-daterange">
                                                <span class="input-group-text bg-primary border-primary text-white">
                                                    <i class="mdi mdi-calendar-range font-13"></i>
                                                </span>
                                            </div>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                                <i class="mdi mdi-autorenew"></i>
                                            </a>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                                <i class="mdi mdi-filter-variant"></i>
                                            </a>
                                        </form>
                                    </div>
                                    <h4 class="page-title">Dashboard</h4>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-8">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="header-title">Category yaratish</h4>
                                        <p class="text-muted font-14"> Web saytning yuqori qismi
                                        </p>
                                        <div class="tab-content">
                                            <div class="tab-pane show active" id="typeahead-preview" role="tabpanel">
                                                <div class="row">
                                                    <form method="post">
                                                        {% csrf_token %}
                                                        <div class="col-lg-12">
                                                            <div class="mb-3">
                                                                <label class="form-label">Nomi</label>
                                                                <span class="twitter-typeahead" style="position: relative; display: inline-block;"><input type="text" class="form-control tt-hint" data-provide="typeahead" readonly="" autocomplete="off" spellcheck="false" tabindex="-1" dir="ltr" style="position: absolute; top: 0px; left: 0px; border-color: transparent; box-shadow: none; opacity: 1; background: none 0% 0% / auto repeat scroll padding-box padding-box rgb(255, 255, 255);"><input type="text" class="form-control tt-input" data-provide="typeahead" id="the-basics" name="name" autocomplete="off" spellcheck="false" dir="auto" style="position: relative; vertical-align: top; background-color: transparent;"><pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: Nunito, sans-serif; font-size: 14.4px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre><div class="tt-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;"><div class="tt-dataset tt-dataset-states"></div></div></span>
                                                            </div>
                                                        </div> <!-- end col -->
                                                        <div class="col">
                                                            <button type="submit" class="btn btn-success rounded-pill">Success</button>
                                                        </div>
                                                    </form>
                                                    </div>
                                                <!-- end row -->
        
                                                <!-- end row -->                      
                                            </div> <!-- end preview-->
                                        </div> <!-- end tab-content-->

                                    </div> <!-- end card-body -->
                                </div> <!-- end card-->
                            </div> <!-- end col -->
                        </div>
                    </div>
                    <!-- container -->

                </div>
 {% endblock %}               

templates/dashboard/category/detail.html
{% extends 'dashboard/base.html' %}
{% block content %}
<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">                                    
                        <div class="page-title-right">
                            <form class="d-flex">
                                <div class="input-group">
                                    <input type="text" class="form-control form-control-light" id="dash-daterange">
                                    <span class="input-group-text bg-primary border-primary text-white">
                                        <i class="mdi mdi-calendar-range font-13"></i>
                                    </span>
                                </div>
                                <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                    <i class="mdi mdi-autorenew"></i>
                                </a>
                                <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                    <i class="mdi mdi-filter-variant"></i>
                                </a>
                            </form>
                        </div>
                        <div class="d-flex justify-content-around align-items-center">
                            <h4 class="page-title" style="display: inline;">Dashboard</h4>
                            <a href="{% url 'dashboard:category-edit' category.id %}" class="btn btn-primary">O`zgartirish</a>
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#centermodal">O`chirish</button>
                            <div class="modal fade" id="centermodal" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="myCenterModalLabel">Categoryni o`chirmoqchimisiz? </h4>
                                            <form method="get" action="{% url 'dashboard:category-delete' category.id %}">
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
                                            </div>
                                            <div class="modal-body">
                                                <input type="checkbox" class="form-check-input" id="customCheckcolor7" required>
                                                <label for="chkb">Ha</label> <br> <br>
                                                <button type="button" class="btn btn-dark" data-bs-dismiss="modal" aria-hidden="true">Qaytish</button>
                                                <button class="btn btn-danger" type="submit">O`chirish</button>
                                            </div>
                                            </form>
                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal-dialog -->
                            </div><!-- /.modal -->

                                    
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
            <div class="row">
                <div class="col-2"></div>
                <div class="col-8">
                     <div class="card">
                            <div class="card-body">
                                <h4 class="header-title mb-3">Category haqida batafsil</h4>
    
                                <div class="table-responsive">
                                    <table class="table mb-0">
                                        <thead class="table-light">
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td><strong>Category nomi</strong> :</td>
                                                <td>{{category.name}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <!-- end table-responsive -->
    
                            </div>
                        </div>
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
        </div>
        <!-- container -->

    </div>
    <!-- content -->

    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
                </div>
                <div class="col-md-6">
                    <div class="text-md-end footer-links d-none d-md-block">
                        <a href="javascript: void(0);">About</a>
                        <a href="javascript: void(0);">Support</a>
                        <a href="javascript: void(0);">Contact Us</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- end Footer -->

</div>
{% endblock %}

templates/dashboard/category/edit.html
{% extends 'dashboard/base.html' %}
{% block content %}
<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">                                    
                        <div class="page-title-right">
                            <form class="d-flex">
                                <div class="input-group">
                                    <input type="text" class="form-control form-control-light" id="dash-daterange">
                                    <span class="input-group-text bg-primary border-primary text-white">
                                        <i class="mdi mdi-calendar-range font-13"></i>
                                    </span>
                                </div>
                                <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                    <i class="mdi mdi-autorenew"></i>
                                </a>
                                <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                    <i class="mdi mdi-filter-variant"></i>
                                </a>
                            </form>
                        </div>
                        <h4 class="page-title">Dashboard</h4>
                    </div>
                </div>
            </div>
            <!-- end row -->
            <div class="row">
                <div class="col-2"></div>
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">Category Tahrirlash</h4>
                            <p class="text-muted font-14"> Web saytning yuqori qismi
                            </p>
                            <div class="tab-content">
                                <div class="tab-pane show active" id="typeahead-preview" role="tabpanel">
                                    <div class="row">
                                        <form method="post">
                                            {% csrf_token %}
                                            <div class="col-lg-12">
                                                <div class="mb-3">
                                                    <label class="form-label"> Sarlavha  </label>
                                                    <span class="twitter-typeahead" style="position: relative; display: inline-block;"><input type="text" class="form-control tt-hint" data-provide="typeahead" readonly="" autocomplete="off" spellcheck="false" tabindex="-1" dir="ltr" style="position: absolute; top: 0px; left: 0px; border-color: transparent; box-shadow: none; opacity: 1; background: none 0% 0% / auto repeat scroll padding-box padding-box rgb(255, 255, 255);"><input type="text" class="form-control tt-input" data-provide="typeahead" id="the-basics" value="{{category.name}}" name="name" autocomplete="off" spellcheck="false" dir="auto" style="position: relative; vertical-align: top; background-color: transparent;"><pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: Nunito, sans-serif; font-size: 14.4px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre><div class="tt-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;"><div class="tt-dataset tt-dataset-states"></div></div></span>
                                                </div>
                                            </div> <!-- end col -->
                                            <div class="col">
                                                <button type="submit" class="btn btn-success rounded-pill">Success</button>
                                            </div>
                                        </form>
                                        </div>                   
                                </div> <!-- end preview-->
                            </div> <!-- end tab-content-->
                        </div> <!-- end card-body -->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
        </div>
        <!-- container -->

    </div>
    <!-- content -->

    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
                </div>
                <div class="col-md-6">
                    <div class="text-md-end footer-links d-none d-md-block">
                        <a href="javascript: void(0);">About</a>
                        <a href="javascript: void(0);">Support</a>
                        <a href="javascript: void(0);">Contact Us</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- end Footer -->

</div>
{% endblock %}

templates/dashboard/category/list.html
{% extends 'dashboard/base.html' %}
{% block content %}
            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">                                    
                                    <div class="page-title-right">
                                        <form class="d-flex">
                                            <div class="input-group">
                                                <input type="text" class="form-control form-control-light" id="dash-daterange">
                                                <span class="input-group-text bg-primary border-primary text-white">
                                                    <i class="mdi mdi-calendar-range font-13"></i>
                                                </span>
                                            </div>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                                <i class="mdi mdi-autorenew"></i>
                                            </a>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                                <i class="mdi mdi-filter-variant"></i>
                                            </a>
                                        </form>
                                    </div>
                                    <h4 class="page-title">Dashboard</h4>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-xl-6">
                                <div class="card">
                                    <div class="card-body">

                                        <h4 class="header-title">Categorylar ro`yxati</h4>
                                        <div class="tab-content">
                                            <div class="tab-pane show active" id="striped-rows-preview" role="tabpanel">
                                                <div class="table-responsive-sm">
                                                    <table class="table table-striped table-centered mb-0">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
                                                                <th>Sarlavha</th>
                                                                <th>Harakatlar</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for cate in category %}
                                                            <tr>
                                                                <td>{{forloop.counter}}</td>
                                                                <td>{{cate.name}}</td>
                                                                <td class="table-action">
                                                                    <a href="{% url 'dashboard:category-detail' cate.id %}" class="action-icon"> <i class=" ri-share-forward-2-line"></i></a>
                                                                </td>
                                                            </tr>
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div> <!-- end table-responsive-->                     
                                            </div> <!-- end preview-->
                                         </div> <!-- end tab-content-->

                                    </div> <!-- end card body-->
                                </div> <!-- end card -->
                            </div>
                        </div>
                    </div>
                    <!-- container -->

                </div>
                <!-- content -->

                <!-- Footer Start -->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
                            </div>
                            <div class="col-md-6">
                                <div class="text-md-end footer-links d-none d-md-block">
                                    <a href="javascript: void(0);">About</a>
                                    <a href="javascript: void(0);">Support</a>
                                    <a href="javascript: void(0);">Contact Us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- end Footer -->

            </div>
{% endblock %}